# Generated by Django 5.0.7 on 2024-08-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=39)),
                ('gender', models.CharField(choices=[('female', 'FEMALE'), ('male', 'MALE'), ('Other', 'OTHER')], max_length=37)),
                ('cource', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=37)),
                ('email', models.EmailField(max_length=37)),
            ],
        ),
    ]
